#!/usr/bin/php
<?php
function y($m)
{ 
	$m = preg_replace("/\./", " x ", $m);
	$m = preg_replace("/@/", " y", $m);
	return $m;
}
function x($y, $z)
{
	$a = file_get_contents($y);
	$a = preg_replace("/(\[x (.*)\])/e", "y(\"\\2\")", $a); // la regex remplace [x ] par rien
	$a = preg_replace("/\[/", "(", $a); // remplace [ par (
	$a = preg_replace("/\]/", ")", $a); // remplace ] par )
	return $a;
}
$r = x($argv[1], $argv[2]);
print $r;
?>